#include "../header_files/database.h"
#include "../header_files/crypto.h"
#include <fstream>
#include <iostream>
#include <sstream>
#include <iomanip>

using namespace std;

// Local helper: converts the byte array generated by sha256_data into a HEX string
string UserDatabase::bytes_to_hex(const array<uint8_t, 32>& bytes) {
    ostringstream oss;
    for (uint8_t b : bytes) {
        oss << hex << setw(2) << setfill('0') << static_cast<int>(b);
    }
    return oss.str();
}

// Loads the users vector from the JSON file
bool UserDatabase::load_from_file(const string& filepath) {
    db_filepath = filepath;
    ifstream file(filepath);

    if (!file.is_open()) {
        cerr << "[DB ERROR] Unable to open file: " << filepath << endl;
        return false;
    }

    try {
        json j;
        file >> j;
        users = j["users"].get<vector<UserAccount>>();
        cout << "[DB] Successfully loaded " << users.size() << " users." << endl;
        return true;
    } catch (const exception& e) {
        cerr << "[DB ERROR] JSON parsing error: " << e.what() << endl;
        return false;
    }
}

void UserDatabase::save_to_file() {
    string tmp_filepath = db_filepath + ".tmp";
    ofstream file(tmp_filepath);
    if (file.is_open()) {
        json j;
        j["users"] = users;
        file << j.dump(4);
        file.close();
        std::rename(tmp_filepath.c_str(), db_filepath.c_str());
    }
}

// Verifies username and password using SHA256(salt + password)
bool UserDatabase::authenticate(const string& username, const string& password) {
    for (const auto& u : users) {
        if (u.username == username) {
            // Calculate the hash of the salted password
            string salted_psw = u.salt + password;
            array<uint8_t, 32> hash_bytes = sha256_data(salted_psw);
            string calculated_hash = bytes_to_hex(hash_bytes);

            //Prevent Timing Attacks using constant-time comparison
            if (u.password_hash.size() != calculated_hash.size()) {
                return false; 
            }
            
            // CRYPTO_memcmp returns 0 if the memory blocks are identical
            return CRYPTO_memcmp(u.password_hash.data(), calculated_hash.data(), calculated_hash.size()) == 0;
        }
    }
    return false; // User not found
}

// Retrieves the user's timestamp balance
bool UserDatabase::get_balance(const string& username, TimestampInfo& out_info) {
    for (const auto& u : users) {
        if (u.username == username) {
            out_info.remaining = u.remaining;
            out_info.consumed = u.consumed;
            out_info.total = u.total;
            return true;
        }
    }
    return false; // User not found
}

// Consumes 1 timestamp and updates the JSON file
bool UserDatabase::consume_timestamp(const string& username) {
    for (auto& u : users) {
        if (u.username == username) {
            if (u.remaining == 0) {
                return false; // Quota exhausted
            }
            u.remaining--;
            u.consumed++;
            save_to_file();
            return true;
        }
    }
    return false; // User not found
}